openvex/vexctl

- README.md
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-123456
Reason: This ID is frequently used as an example of the 2014 CVE-ID syntax change, which allows more than 4 digits in the sequence number.
> switch CVE to official 'sample' ID

- go.mod
- go.sum
- internal/cmd/create.go
- internal/cmd/filter.go
- internal/cmd/merge.go
- pkg/attestation/attestation.go
- pkg/ctl/ctl.go
- pkg/ctl/ctl_test.go
- pkg/ctl/implementation.go
This PR updates all import paths after the main vex repository was renamed to go-vex
/cc @luhring 
> Update import paths to openvex/go-vex 

- .github/workflows/release.yaml
- .gitignore
- .goreleaser.yaml
- .ko.yaml
- Makefile
- scripts/ko-sign-release-images.sh
- scripts/ldflags.sh
- build `vexctl` image using ko
- refactor the release job to generate the provenance
> Build vexctl image and provenance

- pkg/ctl/implementation.go
This PR adjusts the merge impl to lean on `vex.New()` now that we're doing a nontrivial setup of each `vex.VEX` object. This also lets us use the default values for some metadata values, for cases when the corresponding values in `mergeOpts` are not set.
> fix: missing metadata on document merge

- README.md
Noticed that two of the examples in the readme seemed off. Updated with actual command output:
1. New VEX doc: wrong package, wrong justification
2. Merged VEX doc: wrong CVE, context/id/version changes (I can revert these changes if this was my mistake in how I ran)
> Fix examples based on actual command output

- internal/cmd/create.go
This fixes the author, role, id parameters to ensure they are effective. I also noticed that "status notes" was not exposed as a parameter/option, although it was being passed into statement creation.
Closes https://github.com/openvex/vexctl/issues/26
> Fix broken parameters (author, role, id, status notes)

- pkg/ctl/implementation.go
`vexctl filter` would silently ignore any vulnerability identifier that was not a CVE. This PR adds "RUSTSEC", "GHSA", "RHSA" to the supported identifiers.
Fixes: https://github.com/openvex/vexctl/issues/78
> filter: Support more vulnerability identifiers

- internal/cmd/create.go
This commit adds a new flag to specify the impact statement of not_affected VEX statements. It also adds a check to ensure it can only be set when creating a not_affected statement.
Fixes #66
> vexctl create: add --impact-statement

- csaf.json
- examples/csaf/README.md
- examples/csaf/csaf.json
- examples/csaf/openvex.json
- examples/csaf/sbom.spdx.json
- examples/openvex/README.md
- examples/openvex/demo.vex.json
- examples/openvex/document1.vex.json
- examples/openvex/document2.vex.json
- go.mod
- go.sum
- pkg/ctl/implementation.go
This commit modifies vexctl to use the new `vex.Open()` call instead of `vex.Load()`. This lets it automatically load CSAF documents in its subcommands.
It also adds a bunch of examples to test.
~~Hold merging, it needs [go-vex#25](https://github.com/openvex/go-vex/pull/25) and a rebase~~
> Use vex.Open instead of vex.Load to support CSAF

- pkg/ctl/implementation.go
Also removes a redundant `TrimSpace` function call.
Closes #86
Signed-off-by: Feroz Salam <feroz.salam@isovalent.com>
> Add support for PRISMA- identifiers

- internal/cmd/create.go
This PR fixes a bug where the subcomponents flag in the create subcommand was overwriting the product field.
Fixes #88
Thanks @chipzoller for reporting!
> Fix --subcomponents flag

- go.mod
- go.sum
- pkg/ctl/implementation.go
This commit bumps the go-vex libraries to v0.2.1. It reimplements the `vex.StatementFromID()` deprecated function as it was breaking the vexctl tests.
Supersedes https://github.com/openvex/vexctl/pull/94
> bump to openvex/go-vex@v0.2.1

- .github/workflows/release.yaml
This PR adds the ko installer to the release workflow to fix [recent failures in CI when pushing new tags](https://github.com/openvex/vexctl/actions/runs/5602960649/jobs/10248917831).
> Add ko installer to release workflow

- internal/cmd/list.go
- internal/cmd/main.go
- internal/cmd/show.go
Fixes #25 
Intent here is really a lightweight example to drive discussion. 
Deciding if this improves the UX for consumers of the project and provides value, and if so - then discussing format and other supporting documentation.
The bug that this originates from had indicated that there may be some value in this command. If that is no longer the case then we can close out this PR and the Bug all together!
> show subcommand creation for review

- internal/cmd/add.go
- internal/cmd/create.go
- internal/cmd/main.go
- internal/cmd/options.go
This PR creates a new `vexctl add` subcommand. This new subcommand lets users add new vex statements to an existing document. This frees them from having to deal with updating dates, etc.
`vex add` will output the updated document to STDOUT or optionally can write to a new file or edit documents in place.
**Note:** Before merging needs https://github.com/openvex/vexctl/pull/110 and a rebase
> vexctl add subcommand

- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
- .github/workflows/verify.yaml
- .goreleaser.yaml
- .vexctl-bom-config.yaml
- Makefile
- bump golangci-lint to v1.55.x
- add sboms and revamp the provanance with k8s-release actions tools
- cleanup
- add snapshot job
release rehearsal: https://github.com/cpanato/vexctl/releases/tag/v99.99.00 / https://github.com/cpanato/vexctl/actions/runs/6955168726
> revamp release job, cleanups and add snapshot job

- .github/workflows/release.yaml
- .github/workflows/snapshot.yaml
Now that the release-actions repo has been finally migrated to the kubernetes organization, we update the workflows to point to the new repo.
Signed-off-by: Adolfo Garcia Veytia (puerco) <puerco@chainguard.dev>
> Move release actions to kubernetes-sigs

- go.mod
- pkg/attestation/attestation.go
- pkg/ctl/implementation.go
This is a large PR that fixes keyless verification of the OpenVEX attestations as reported in https://github.com/openvex/vexctl/issues/143 
This is a solid but temporary fix, the functionality in this PR will be moved to `openvex/discoery` and an upcoming trust module but it should do the work while we finish those new modules.
**The summary of changes**
1. We now upload the signatures to rekor
2. Results of signing operation and appending to the tlog are now recorded in the attestation struct
3. We now add the needed  OCI annotations when attaching images to enable keyless verification
The main goal is to add two missing features:
1. Register the signature data to Rekor<br>
After signing, we now register the signature in the sigstore transparency
log. This is essential to allow for …
> Fix keyless verification of openvex attesatations

- internal/cmd/generate.go
- internal/cmd/main.go
- pkg/ctl/ctl.go
- pkg/ctl/implementation.go
- pkg/ctl/implementation_test.go
- pkg/ctl/testdata/templates/oci-vexctl.openvex.json
This PR introduces a new subcommand to vexctl: `generate`
With `vexctl generate`, users can automate the generation of VEX data from golden templates with known vex statements:
```
Usage:
vexctl generate [flags] [product_id]
Examples:
vexctl generate "pkg:apk/wolfi/git
Flags:
--author string        author to record in the new document (default "Unknown Author")
--author-role string   optional author role to record in the new document
--file string          file to write the document to (default is STDOUT)
-h, --help                 help for generate
--id string            ID string for the new VEX document (autogenerated by default)
--init                 initialize a new templates directory in the path specified with -t
-p, --product string       main identifier of the product, a package …
```
> vexctl generate

- pkg/ctl/implementation.go
The current generated template produces errors for the markdown linter.
This PR fixes that.
> Fix linter errors for the template

- internal/cmd/add.go
- internal/cmd/create.go
- internal/cmd/options.go
- internal/cmd/options_test.go
This PR adds supports for having multiple `--product` flags.
Fixes https://github.com/openvex/vexctl/issues/215.
> fix(create): support multiple `--product` flags

- internal/cmd/options.go
- internal/cmd/options_test.go
This is an initial implementation that adds support to vulnerability aliases as documented in the [spec](https://github.com/openvex/spec/blob/52dd5645b4a37e723a27e7ac22f7e0e4abb5deed/OPENVEX-SPEC.md?plain=1#L333).
Note that support is only added when creating a new Vex document or adding a new statement. It doesn't support filtering or merging based on aliases.
Closes https://github.com/openvex/vexctl/issues/219
> Add support to vulnerability aliases

- pkg/ctl/ctl.go
- pkg/ctl/ctl_test.go
- pkg/ctl/implementation.go
This PR fixes a few copyright headers which we forgot to update after the donation of the project to @ossf and which are causing warning to be printed on CI runs.
> Fix Copyright in Boilerplates

- pkg/ctl/implementation.go
Small suggestion to improve the generated template README with:
1. Update the example command.
2. The status referenced `fixed`, but the text `under investigation`.
3. Some formatting improvements.
4. Typo fixes.
> Improve the generated template README

- .goreleaser.yaml
The artifact naming scheme was reversed in https://github.com/openvex/vexctl/commit/ed4170beb4943f84a6d460382ea4580ae7f4590d and the installer action is broken. This change should correct the names and restore the installer.
> Reverse platform+os naming cheme
